matcha_drink/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.urls import include, path

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path('tentang_kami/', include('tentangkami.urls')),
    path('menu/', include('menu.urls')),
    path('testimonial/', include('testimonial.urls')),
    path('otentikasi/', include('otentikasi.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.menu, name='menu'),
    path('cart/<int:cart_id>', views.cart_detail, name='cart'),
    path('ajax_search', views.search_menu, name='ajax_search'),
]

otentikasi/urls.py
from django.urls import path
from . import views

app_name = 'otentikasi'

urlpatterns = [
    path('login', views.ajax_login, name='login'),
    path('register', views.ajax_register, name='register'),
    path('logout', views.ajax_logout, name='logout'),
]

tentangkami/urls.py
from django.urls import path
from . import views

app_name = 'tentangkami'

urlpatterns = [
    path('', views.tentang_kami, name='tentangkami'),
    path('masukan_data/',views.masukan_data),
    path('get_data/',views.get_data),
]

testimonial/urls.py
from django.urls import path
from . import views

app_name = 'testimonial'

urlpatterns = [
    path('', views.testimonial, name='testimonial'),
    path('json/', views.get_JSON_testimonial, name='testimonial_JSON')
]

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
]

web/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Match'A Drink v2{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700,800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    {% block style %}{% endblock %}
  </head>
  <body>
    <div id="container" class="position-relative">
      <!-- Navbar -->
      <div class="fixed-top bg-white">
        <nav class="navbar navbar-default navbar-expand-md navbar-light">
          <a class="navbar-brand" href="{% url 'web:index' %}">Match'A Drink v2</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="ml-auto navbar-nav">
              {% with url_name=request.resolver_match.url_name %}
              <li class="nav-item">
                <a class="nav-link{% if url_name == 'index' %} active{% endif %}" href="{% url 'web:index' %}">Beranda</a>
              </li>
              <li class="nav-item">
                <a class="nav-link{% if url_name == 'menu' %} active{% endif %}" href="{% url 'menu:menu' %}">Menu</a>
              </li>
              <li class="nav-item">
                <a class="nav-link{% if url_name == 'tentang' %} active{% endif %}" href="{% url 'tentangkami:tentangkami'%}">Tentang Kami</a>
              </li>
              <li class="nav-item">
                <a class="nav-link{% if url_name == 'testimoni' %} active{% endif %}" href="{% url 'testimonial:testimonial' %}">Testimoni</a>
              </li>
              {% endwith %}
              {% if not user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link" href="#" data-toggle="modal" data-target="#login-modal">Login</a>
              </li>
              {% else %}
              <li class="nav-item">
                  <span class="nav-link">Hi! {{ user.username }}</span>
              </li>
              <li class="nav-item">
                  <a class="nav-link" id="logout" href="#">Logout</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </nav>
      </div>
      <!-- Content -->
      {% block content %}{% endblock %}
      <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="login-modal-label" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                  <div class="modal-header">
                      <div class="modal-title">
                          <!-- <h5 class="modal-title" id="login-modal-label">Login</h5>
                          <h5 class="modal-title" id="signup-modal-label">Daftar</h5> -->
                          <button type="button" class="header-modal clicked" name="button-modal-masuk">Masuk</button>
                          <button type="button" class="header-modal not-clicked" name="button-modal-daftar">Daftar</button>
                      </div>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                      </button>
                  </div>
                  <div class="modal-body">

                      <form class="form-login mx-auto" id="form-login" method="POST" action="{% url 'otentikasi:login' %}">
                          <h1 class="t-green">Masuk Yuk</h1>
                          <div id="form_login"></div>
                          <button type="button" name="button-masuk" class="btn btn-success">Masuk</button>
                          <button type="button" class="btn btn-outline-success" data-dismiss="modal">Kembali</button>
                      </form>
                      <form class="form-login mx-auto hidden" id="form-regis" method="POST" action="{% url 'otentikasi:register' %}">
                          <h1 class="t-green">Daftar Yuk</h1>
                          <div id="form_register"></div>
                          <button type="button" name="button-daftar" class="btn btn-success">Daftar</button>
                          <button type="button" class="btn btn-outline-success" data-dismiss="modal">Kembali</button>
                      </form>
                  </div>
                  <div class="modal-footer">


                  </div>
              </div>
          </div>
      </div>
      <!-- Footer -->
      <footer class="position-absolute b-darkgreen d-flex justify-content-center align-items-center">
        <div class="font-weight-bold">
          © Lulus Pepew Aamiin 2019
        </div>
      </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src={% static 'homepage.js' %}></script>
    {% block script %}{% endblock %}
  </body>
</html>