matcha_drink/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.urls import include, path

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path('tentang_kami/', include('tentangkami.urls')),
    path('menu/', include('menu.urls')),
    path('testimonial/', include('testimonial.urls')),
    path('otentikasi/', include('otentikasi.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.menu, name='menu'),
    path('cart/<int:cart_id>', views.cart_detail, name='cart'),
    path('ajax_search', views.search_menu, name='ajax_search'),
]

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
]

menu/models.py
from django.contrib.auth.models import User

from django.db import models

# Create your models here.
class Menu(models.Model):
    name = models.CharField(max_length=50)
    price = models.PositiveIntegerField()
    description = models.TextField()
    favorite = models.BooleanField(default=False)
    image = models.FileField(upload_to='menu/')

    def __str__(self):
        return self.name

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        all_orders = []
        for order in self.order_set.all():
            all_orders.append(str(order))

        return '{}: {}'.format(self.user, ', '.join(all_orders))


class Order(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    amount = models.PositiveSmallIntegerField()

    def __str__(self):
        return '{} {}'.format(self.amount, self.menu)

menu/forms.py
from django import forms

from .models import Menu, Order

class OrderForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for menu in Menu.objects.all():
            self.fields['menu_' + str(menu.id)] = forms.IntegerField(
                min_value=0,
                max_value=32767,
                initial=0,
            )

    def clean(self):
        super().clean()

        total = 0
        for value in self.cleaned_data.values():
            total += value
        if total == 0:
            raise forms.ValidationError('Harus pesan minimal 1 minuman.')

menu/views.py
from django.core import serializers
from django.http import HttpResponse
from django.shortcuts import Http404, get_object_or_404, redirect, render
from django.urls import reverse

from .forms import OrderForm
from .models import Cart, Menu, Order


def menu(request):
    if request.method == 'POST' and request.user.is_authenticated:
        form = OrderForm(request.POST)
        if form.is_valid():
            user = request.user
            if user is not None:
                cart = Cart(user=user)
            else:
                cart = Cart(user='user')

            cart.save()
            for key, value in form.cleaned_data.items():
                if key[:5] == 'menu_' and int(value) > 0:
                    order = Order(
                        cart=cart,
                        menu=get_object_or_404(Menu, id=key[5:]),
                        amount=value,
                    )
                    order.save()

            return redirect(reverse('menu:cart', kwargs={'cart_id': cart.id}))

    else:
        form = OrderForm()

    favorite_menu = Menu.objects.filter(favorite=True)
    for each in favorite_menu:
        each.form_field = form['menu_' + str(each.id)]

    other_menu = Menu.objects.filter(favorite=False)
    for each in other_menu:
        each.form_field = form['menu_' + str(each.id)]

    context = {
        'favorite_menu': favorite_menu,
        'other_menu': other_menu,
        'form': form,
    }

    return render(request, 'menu/menu.html', context)


def cart_detail(request, cart_id):
    cart = get_object_or_404(Cart, id=cart_id)
    all_orders = cart.order_set.all()

    subtotal = 0
    for order in all_orders:
        subtotal += order.amount * order.menu.price

    context = {
        'orders': cart.order_set.all(),
        'subtotal': subtotal,
    }

    return render(request, 'menu/cart.html', context)

def search_menu(request):
    if request.is_ajax():
        filtered = Menu.objects.filter(name__icontains=request.GET.get('q', ''))
        data = serializers.serialize('json', filtered)
        return HttpResponse(data, content_type='application/json')
    raise Http404()

menu/templates/menu/cart.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block style %}
<link rel="stylesheet" href="{% static 'menu/cart.css' %}">
{% endblock %}

{% block content %}
<section id="cart">
  <div>
    <h1>Pesanan</h1>
    <div class="card p-4 my-4">
      <div class="container-fluid">
        {% for order in orders %}
        <div class="row align-items-center my-3">
          <div class="col-4 col-md-2">
            <img class="image" src="{{ order.menu.image.url }}">
          </div>
          <div class="name col-8 col-md-6">
            {{ order.menu.name }}
          </div>
          <div class="col-4 col-md-1 text-right">
            {{ order.amount }}
          </div>
          <div class="col-8 col-md-3">
            Rp {{ order.menu.price|intcomma }}
          </div>
        </div>
        {% endfor %}
        <div class="d-flex justify-content-end">
          <div id="subtotal" class="py-3 px-4 b-darkgreen d-flex flex-column flex-md-row">
            <div>
            Subtotal
            </div>
            <div class="ml-md-5">
              Rp {{ subtotal|intcomma }}
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="buttons mt-4">
      <a href="{% url 'menu:menu' %}" class="button b-green">Pesan</a>
      <a href="{% url 'menu:menu' %}" class="button b-white">Kembali</a>
    </div>
  </div>
</section>
{% endblock %}

menu/templates/menu/menu.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block style %}
<link rel="stylesheet" href="{% static 'menu/menu.css' %}">
<style>
.btn-plus {
  background-image: url("{% static 'menu/count_plus.svg' %}");
  right: 0;
}
.btn-min {
  background-image: url("{% static 'menu/count_min.svg' %}");
  left: 0;
}
</style>
{% endblock %}

{% block content %}
<section id="header" class="d-flex b-green position-relative">
  <div class="d-flex align-items-center position-relative z-1">
    <h1>Yuk Pesan</h1>
  </div>
  <img src="{% static 'menu/menu_photo.png' %}" class="position-absolute">
</section>
<section id="menu" style="min-height: 80vh">
  <div>
    <form method="POST">
      <div class="card mt-5">
        <input class="form-control" type="text" name="q" placeholder="Cari Menu">
      </div>
      {% csrf_token %}
      {{ form.errors }}
      <div class="menu">
        <h1>Menu Favorit</h1>
        <div class="container-fluid">
          {% for menu in favorite_menu %}
          <div class="row align-items-center">
            <div class="col-6 col-md-2">
              <img src="{{ menu.image.url }}">
            </div>
            <div class="col-6 col-md-2">
              <span class="name">{{ menu.name }}</span>
              <br>
              <span class="price">Rp {{ menu.price|intcomma }}</span>
            </div>
            <div class="desc col-6 col-md-5">
              {{ menu.description }}
            </div>
            <div class="col-6 col-md-3">
              {% if user.is_authenticated %}
              <div class="input-number position-relative">
                <button onclick="this.parentNode.querySelector('input').stepDown()" class="btn-min"></button>
                {{ menu.form_field }}
                <button onclick="this.parentNode.querySelector('input').stepUp()" class="btn-plus"></button>
              </div>
              {% endif %}
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="menu">
        <h1>Menu Lainnya</h1>
        <div class="container-fluid">
          {% for menu in other_menu %}
          <div class="row align-items-center">
            <div class="col-6 col-md-2">
              <img src="{{ menu.image.url }}">
            </div>
            <div class="col-6 col-md-2">
              <span class="name">{{ menu.name }}</span>
              <br>
              <span class="price">Rp {{ menu.price|intcomma }}</span>
            </div>
            <div class="desc col-6 col-md-5">
              {{ menu.description }}
            </div>
            <div class="col-6 col-md-3">
              {% if user.is_authenticated %}
              <div class="input-number position-relative">
                <button onclick="this.parentNode.querySelector('input').stepDown()" class="btn-min"></button>
                {{ menu.form_field }}
                <button onclick="this.parentNode.querySelector('input').stepUp()" class="btn-plus"></button>
              </div>
              {% endif %}
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="menu search"></div>
      <div class="my-5">
        {% if user.is_authenticated %}
        <button type="submit" class="button b-green">Pesan</button>
        {% else %}
        <h2>Masuk dahulu agar dapat memesan</h2>
        {% endif %}
      </div>
    </form>
  </div>
</section>
{% endblock %}

{% block script %}
<script>
$('form').on('click', 'button:not([type="submit"])', function(e){
  e.preventDefault();
})

var search_url = "{% url 'menu:ajax_search' %}"
{% if user.is_authenticated %}
var authenticated = true
{% else %}
var authenticated = false
{% endif %}
</script>
<script src="{% static 'menu/search.js' %}"></script>
{% endblock %}

menu/templates/menu/search.html
<div class="menu">
  <h1>Hasil Pencarian</h1>
  <div class="container-fluid">
    {% for menu in search_result %}
    <div class="row align-items-center">
      <div class="col-6 col-md-2">
        <img src="{{ menu.image.url }}">
      </div>
      <div class="col-6 col-md-2">
        <span class="name">{{ menu.name }}</span>
        <br>
        <span class="price">Rp {{ menu.price|intcomma }}</span>
      </div>
      <div class="desc col-6 col-md-5">
        {{ menu.description }}
      </div>
      <div class="col-6 col-md-3">
        <div class="input-number position-relative">
          <button onclick="this.parentNode.querySelector('input').stepDown()" class="btn-min"></button>
          {{ menu.form_field }}
          <button onclick="this.parentNode.querySelector('input').stepUp()" class="btn-plus"></button>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>