matcha_drink/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.urls import include, path

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path('tentang_kami/', include('tentangkami.urls')),
    path('menu/', include('menu.urls')),
    path('testimonial/', include('testimonial.urls')),
    path('otentikasi/', include('otentikasi.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testimonial/urls.py
from django.urls import path
from . import views

app_name = 'testimonial'

urlpatterns = [
    path('', views.testimonial, name='testimonial'),
    path('json/', views.get_JSON_testimonial, name='testimonial_JSON')
]

web/urls.py
from django.urls import path
from . import views

app_name = 'web'

urlpatterns = [
    path('', views.index, name='index'),
]

testimonial/models.py
from django.db import models

# Create your models here.
class Testimonial(models.Model):
    name = models.CharField(max_length=50, blank=False)
    message = models.CharField(max_length=300, blank=False)
    time = models.DateTimeField(auto_now_add=True, blank=False)

    def get_dict(self):
        return {
            'name':self.name,
            'message':self.message,
            'time':self.time
        }

testimonial/forms.py
from django import forms

class TestimoniForm(forms.Form):
    message = forms.CharField(label="Testimoni", widget=forms.Textarea(attrs={
        'rows': 6,
        'style': 'resize:none;',
        'class': 'form-control',
        'type' : 'text',
        'placeholder': 'Testimoninya :)',
        'required': True,
    }))

testimonial/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, HttpResponse, redirect
from django.http import JsonResponse
from .models import Testimonial
from .forms import TestimoniForm
import json

# Create your views here.
def testimonial(request):
    responses = {}
    if request.method == 'POST':
        if request.is_ajax():
            if request.user.is_authenticated:
                form = TestimoniForm(request.POST)
                if form.is_valid():
                    name = request.user.username
                    message = form.cleaned_data['message']
                    Testimonial(name=name, message=message).save()
                    return JsonResponse({'success': True})
        return JsonResponse({'success': False})
    else:
        form = TestimoniForm()
        responses['form'] = form
        return render(request, 'testimonial/testimonial.html', responses)

def get_JSON_testimonial(request):
    data = {
        'data':[i.get_dict() for i in Testimonial.objects.all()[::-1][:5]],
    }
    return JsonResponse(data=data)

testimonial/templates/testimonial/testimonial.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'testimonial/style.css' %}">
{% endblock %}

{% block content %}
<section id="header" class="d-flex b-green position-relative">
    <div class="d-flex align-items-center position-relative z-1">
        <h1>Testimoni</h1>
    </div>
    <img src="{% static 'testimonial/testimonial_photo.png' %}" class="position-absolute">
</section>
<section id="testimonial" class="d-flex flex-column flex-md-row">
    <div class="row">
        <div class="col-md">
            <div class="col-mw">
                {% if user.is_authenticated %}
                <form action='' method="POST" id="form-testi">
                    {% csrf_token %}
                    {{ form.message.label_tag }}
                    {{ form.message }}
                    <br>
                    <input id="testi-sub" type="button" class="button b-green" value="Submit">
                </form>
                {% else %}
                <h1 style="margin-top:2rem;">Masuk dulu ya</h1>
                {% endif %}
            </div>
        </div>
        <div class="col-md flex-row" id="testimonial-result">
            <!-- json -->
        </div>
    </div>

{% block script %}
<script>
var url = '{% url "testimonial:testimonial_JSON" %}'
var url2 = '{% url "testimonial:testimonial" %}'
</script>
<script src="{% static 'testimonial/testimonial.js' %}"></script>
{% endblock %}

</section> 
{% endblock %}